name: Build LaTeX
on:
  push:
    paths:
      - "files/cv.tex"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: files/cv.tex
        
      - name: Upload PDF to Repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files/cv.pdf
          git commit -m "update cv"
          git push
